apiVersion: v1
clusters:
- cluster:
    server: https://c114-e.eu-de.containers.cloud.ibm.com:30439
  name: dev_sf_cluster/cecgtqdf00qdkg190040
- cluster:
    server: https://c114-e.eu-de.containers.cloud.ibm.com:30439
  name: c114-e-eu-de-containers-cloud-ibm-com:30439
contexts:
- context:
    cluster: dev_sf_cluster/cecgtqdf00qdkg190040
    namespace: default
    user: ""
  name: dev_sf_cluster/cecgtqdf00qdkg190040
- context:
    cluster: c114-e-eu-de-containers-cloud-ibm-com:30439
    namespace: default
    user: IAM#awhalley@ie.ibm.com/c114-e-eu-de-containers-cloud-ibm-com:30439
  name: default/c114-e-eu-de-containers-cloud-ibm-com:30439/IAM#awhalley@ie.ibm.com
current-context: default/c114-e-eu-de-containers-cloud-ibm-com:30439/IAM#awhalley@ie.ibm.com
kind: Config
preferences: {}
users:
- name: IAM#awhalley@ie.ibm.com/c114-e-eu-de-containers-cloud-ibm-com:30439
  user:
    token: sha256~LmgqI1tJsvThrAuKf1_abbnMTcY3h89h156f8Br_SJI
